src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
  /**
   * @ORM\Id
   * @ORM\GeneratedValue
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $name;

  /**
   * @ORM\Column(type="datetime")
   */
  private $start_date;

  /**
   * @ORM\Column(type="datetime")
   */
  private $end_date;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $location;

  /**
   * @ORM\Column(type="string", length=100)
   */
  private $city;

  /**
   * @ORM\Column(type="string", length=5)
   */
  private $postal_code;

  /**
   * @ORM\Column(type="decimal", precision=5, scale=2)
   * @Assert\GreaterThanOrEqual(0)
   */
  private $price;

  /**
   * @ORM\Column(type="boolean", options={"default"=false})
   */
  private $active;

  /**
   * @ORM\ManyToMany(targetEntity=User::class, mappedBy="Events")
   */
  private $users;

  /**
   * @ORM\Column(type="text", nullable=true)
   */
  private $description;

  /**
   * @ORM\Column(type="integer")
   */
  private $seats;

  /**
   * @ORM\ManyToMany(targetEntity=Collective::class, mappedBy="events")
   */
  private $collectives;

  public function __construct()
  {
      $this->users = new ArrayCollection();
      $this->collectives = new ArrayCollection();
  }

  public function __toString()
  {
    return $this->name;
  }

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getName(): ?string
  {
    return $this->name;
  }

  public function setName(string $name): self
  {
    $this->name = $name;

    return $this;
  }

  public function getStartDate(): ?\DateTimeInterface
  {
    return $this->start_date;
  }

  public function setStartDate(\DateTimeInterface $start_date): self
  {
    $this->start_date = $start_date;

    return $this;
  }

  public function getEndDate(): ?\DateTimeInterface
  {
    return $this->end_date;
  }

  public function setEndDate(\DateTimeInterface $end_date): self
  {
    $this->end_date = $end_date;

    return $this;
  }

  public function getLocation(): ?string
  {
    return $this->location;
  }

  public function setLocation(?string $location): self
  {
    $this->location = $location;

    return $this;
  }

  public function getCity(): ?string
  {
    return $this->city;
  }

  public function setCity(string $city): self
  {
    $this->city = $city;

    return $this;
  }

  public function getPostalCode(): ?string
  {
    return $this->postal_code;
  }

  public function setPostalCode(string $postal_code): self
  {
    $this->postal_code = $postal_code;

    return $this;
  }

  public function getPrice(): ?string
  {
    return $this->price;
  }

  public function setPrice(string $price): self
  {
    $this->price = $price;

    return $this;
  }

  public function getActive(): ?bool
  {
    return $this->active;
  }

  public function setActive(bool $active): self
  {
    $this->active = $active;

    return $this;
  }

  /**
   * @return Collection|User[]
   */
  public function getUsers(): Collection
  {
      return $this->users;
  }

  public function addUser(User $user): self
  {
      if (!$this->users->contains($user)) {
          $this->users[] = $user;
          $user->addEvent($this);
      }

      return $this;
  }

  public function removeUser(User $user): self
  {
      if ($this->users->removeElement($user)) {
          $user->removeEvent($this);
      }

      return $this;
  }

  public function getDescription(): ?string
  {
      return $this->description;
  }

  public function setDescription(?string $description): self
  {
      $this->description = $description;

      return $this;
  }

  public function getSeats(): ?int
  {
      return $this->seats;
  }

  public function setSeats(int $seats): self
  {
      $this->seats = $seats;

      return $this;
  }

  /**
   * @return Collection|Collective[]
   */
  public function getCollectives(): Collection
  {
      return $this->collectives;
  }

  public function addCollective(Collective $collective): self
  {
      if (!$this->collectives->contains($collective)) {
          $this->collectives[] = $collective;
          $collective->addEvent($this);
      }

      return $this;
  }

  public function removeCollective(Collective $collective): self
  {
      if ($this->collectives->removeElement($collective)) {
          $collective->removeEvent($this);
      }

      return $this;
  }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options): void
  {
    $builder
      ->add('name', TextType::class)
      ->add('start_date', DateTimeType::class)
      ->add('end_date', DateTimeType::class)
      ->add('location', TextType::class, ['required' => false])
      ->add('city', TextType::class)
      ->add('postal_code', TextType::class)
      ->add('price', MoneyType::class)
      ->add('seats', IntegerType::class)
      ->add('description', TextareaType::class)
      ->add('active', CheckboxType::class, ['required' => false]);
  }

  public function configureOptions(OptionsResolver $resolver): void
  {
    $resolver->setDefaults([
      'data_class' => Event::class,
    ]);
  }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\User;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
  private $entityManager;
  private $userRepository;

  public function __construct(EntityManagerInterface $entityManager, UserRepository $userRepository)
  {
    $this->entityManager = $entityManager;
    $this->userRepository = $userRepository;
  }

  /**
   * @Route("/", name="event_index", methods={"GET"})
   */
  public function index(EventRepository $eventRepository): Response
  {
    /** @var \App\Entity\User $user */
    $user = $this->getUser();

    return $this->render('/event/index.html.twig', [
      'all_next_events' => $eventRepository->findAllNextEvents(),
      'next_events_active' => $eventRepository->findNextEventsActive(),
      'past_events_active' => $eventRepository->findPastEventsActive(),
      'user' => $user
    ]);
  }

  /**
   * @Route("/new", name="event_new", methods={"GET", "POST"})
   * @IsGranted("ROLE_ADMIN")
   */
  public function new(Request $request, MailerInterface $mailer): Response
  {
    $event = new Event();
    $form = $this->createForm(EventType::class, $event);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $this->entityManager->persist($event);
      $this->entityManager->flush();

      $response = $this->forward('App\Controller\MailerController::sendEmailToAll', [
        'event' => $event,
        'users' => $this->userRepository->findAll(),
        'data' => [
          'subject' => "Prochainement : "+ $event->getName(),
          'text' => ''
        ]
      ]);

      return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('event/new.html.twig', [
      'event' => $event,
      'form' => $form,
    ]);
  }

  /**
   * @Route("/{id}", name="event_show", methods={"GET"})
   */
  public function show(Event $event): Response
  {
    /** @var \App\Entity\User $user */
    $user = $this->getUser();
    return $this->render('event/show.html.twig', [
      'event' => $event,
      'user' => $user
    ]);
  }

  /**
   * @Route("/{id}/edit", name="event_edit", methods={"GET", "POST"})
   * @IsGranted("ROLE_ADMIN")
   */
  public function edit(Request $request, Event $event): Response
  {
    $form = $this->createForm(EventType::class, $event);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $this->entityManager->flush();

      $response = $this->forward('App\Controller\MailerController::sendEmail', [
        'event' => $event,
        'users' => $this->userRepository->findAll(),
        'data' => [
          'subject' => "L'évènement "+ $event->getName() +" auquel vous participez a été modifié !",
          'text' => ''
        ]
      ]);

      return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('event/edit.html.twig', [
      'event' => $event,
      'form' => $form,
    ]);
  }

  /**
   * @Route("/{id}", name="event_delete", methods={"POST"})
   * @IsGranted("ROLE_ADMIN")
   */
  public function delete(Request $request, Event $event): Response
  {
    if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
      $this->entityManager->remove($event);
      $this->entityManager->flush();
    }

    return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
  }

  /**
   * @Route("/{id}/add_participant", name="event_add_participant", methods={"POST"})
   * @IsGranted("ROLE_USER")
   */
  public function addParticipant(Request $request, Event $event): Response
  {
    if ($this->isCsrfTokenValid('put' . $event->getId(), $request->request->get('_token'))) {
      if ($this->getUser() && count($event->getUsers()) < $event->getSeats()) {
        $event->addUser($this->getUser());
        $this->entityManager->persist($event);
        $this->entityManager->flush();
      }
    }

    return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
  }

  /**
   * @Route("/{id}/remove_participant", name="event_remove_participant", methods={"POST"})
   * @IsGranted("ROLE_USER")
   */
  public function removeParticipant(Request $request, Event $event): Response
  {
    if ($this->isCsrfTokenValid('put' . $event->getId(), $request->request->get('_token'))) {
      if ($this->getUser()) {
        $users = $event->getUsers();
        for ($i = 0; $i < count($users); $i++) {
          if ($users[$i] == $this->getUser()) {
            $event->removeUser($users[$i]);
          }
        }
        $this->entityManager->persist($event);
        $this->entityManager->flush();
      }
    }

    return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
  }
}

templates/event/_add_participant_form.html.twig
<form method="post" action="{{ path('event_add_participant', {'id': event.id}) }}">
  <input type="hidden" name="_token" value="{{ csrf_token('put' ~ event.id) }}">
  <button class="btn">Participer</button>
</form>

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_remove_participant_form.html.twig
<form method="post" action="{{ path('event_remove_participant', {'id': event.id}) }}">
  <input type="hidden" name="_token" value="{{ csrf_token('put' ~ event.id) }}">
  <button class="btn">Se désinscrire</button>
</form>

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les events{% endblock %}

{% block body %}
  {% if is_granted('ROLE_ADMIN') %}
    <section class="grid grid-cols-3 gap-4 my-10">
      <div class="col-span-3 flex justify-between">
        <h2 class="font-bold uppercase">Tous les évènements à venir</h2>
        <a class="border border-gray-500 rounded-xl px-3 block ml-auto" href="{{ path('event_new') }}">Nouveau</a>
      </div>
      {% for event in all_next_events %}
        {% include "partials/card.html.twig" with {'event' : event} %}
      {% else %}
        <p>Ajoutez un nouvel évènement</p>
        <a class="border border-gray-500 rounded-xl px-3 block ml-auto" href="{{ path('event_new') }}">Nouveau</a>
      {% endfor %}
    </section>
  {% else %}
    <section class="grid grid-cols-3 gap-4 my-10">
      <div class="col-span-3 flex justify-between">
        <h2 class="font-bold uppercase">évènements à venir</h2>
        {% if is_granted('ROLE_ADMIN') %}
          <a class="border border-gray-500 rounded-xl px-3 block ml-auto" href="{{ path('event_new') }}">Nouveau</a>
        {% endif %}
      </div>
      {% for event in next_events_active %}
        {% include "partials/card.html.twig" with {'event' : event} %}
      {% else %}
        <p class="col-span-3 text-center">Il n'y a pas d'évènement programmé pour le moment</p>
      {% endfor %}
    </section>
    <section class="grid grid-cols-3 gap-4 my-10">
      <h2 class="col-span-3 font-bold uppercase">évènements passés</h2>
      {% for event in past_events_active %}
        {% include "partials/card.html.twig" with {'event' : event} %}
      {% else %}
        <p class="col-span-3 text-center">Il n'y a pas d'évènement</p>
      {% endfor %}
    </section>
  {% endif %}
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
  <div class="grid grid-cols-3">
    <div class="flex items-center col-span-1">
      <a class="flex gap-3 items-center button"
         href="{{ path('event_index') }}">
        <span class="w-5 h-5">{{ source('@assets_path'~asset('svg/back.svg')) }}</span>
        back to list
      </a>
    </div>
    <div class="">
      <h1 class="flex-1">{{ event.name }}</h1>
    </div>
    <div class="flex items-center justify-center">
      {% if is_granted('ROLE_ADMIN') %}
        <a class="button" href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
        {{ include('event/_delete_form.html.twig') }}
      {% endif %}
    </div>
    <p class="col-span-3">{{ event.description }}</p>
  </div>
  <table class="table">
    <tbody>
    <tr>
      <th>Date</th>
      <td>{{ event.startDate ? event.startDate|date('Y-m-d H:i:s') : '' }}</td>
    </tr>
    <tr>
      <th>Date</th>
      <td>{{ event.endDate ? event.endDate|date('Y-m-d H:i:s') : '' }}</td>
    </tr>
    <tr>
      <th>Location</th>
      <td>{{ event.location }}</td>
    </tr>
    <tr>
      <th>City</th>
      <td>{{ event.city }}</td>
    </tr>
    <tr>
      <th>Postal code</th>
      <td>{{ event.postalCode }}</td>
    </tr>
    <tr>
      <th>Price</th>
      <td>{{ event.price }}</td>
    </tr>
    {% if is_granted('ROLE_ADMIN') %}
      <tr>
        <th>Number of places</th>
        <td>{{ event.seats }}</td>
      </tr>
      <tr>
        <th>Active</th>
        <td>{{ event.active ? 'Yes' : 'No' }}</td>
      </tr>
    {% endif %}
    </tbody>
  </table>
  {% include "/event/_add_participant_form.html.twig" %}

{% endblock %}